# Generated by Django 4.0.3 on 2022-05-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_user_feed_feed_cust_user_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='cust',
        ),
        migrations.AddField(
            model_name='user',
            name='feed',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='feedback.feed'),
            preserve_default=False,
        ),
    ]
