# Generated by Django 4.0.3 on 2022-05-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_rename_name_feed_contact_remove_user_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='contact',
            new_name='name',
        ),
    ]
