# Generated by Django 4.0.3 on 2022-05-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_feed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='feed',
        ),
        migrations.AddField(
            model_name='feed',
            name='cust',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='feedback.user'),
            preserve_default=False,
        ),
    ]
