# Generated by Django 4.0.3 on 2022-05-25 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_login'),
        ('feedback', '0012_remove_feed_cust_user_feed_alter_feed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='name',
        ),
        migrations.AddField(
            model_name='feed',
            name='signUp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pages.signup'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
