# Generated by Django 4.0.3 on 2022-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_remove_feed_name_feed_signup_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
