# Generated by Django 4.0.3 on 2022-05-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_feed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='name',
        ),
    ]
