# Generated by Django 4.0.3 on 2022-05-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_remove_feed_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name': 'usersinfo'},
        ),
    ]
