# Generated by Django 4.0.3 on 2022-05-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_alter_feed_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={},
        ),
    ]
