# Generated by Django 4.0.3 on 2022-05-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
