# Generated by Django 4.0.3 on 2022-05-26 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_car_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='fuel',
        ),
    ]
