# Generated by Django 4.0.3 on 2022-05-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=70),
        ),
    ]
