# Generated by Django 4.0.3 on 2022-05-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_signup_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='address',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
    ]
