# Generated by Django 4.0.3 on 2022-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_signupt_signupform'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupform',
            name='email',
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
    ]
