# Generated by Django 4.0.3 on 2022-05-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_signupform_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signupform',
            new_name='signUp',
        ),
    ]
