# Generated by Django 4.0.3 on 2022-05-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminLogin',
        ),
    ]
