# Generated by Django 4.0.3 on 2022-05-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminLogin',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='signUp',
        ),
    ]
