# Generated by Django 4.0.3 on 2022-05-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'usersinfo'},
        ),
    ]
